### ISSUE TITLE
Every request says could not be added, added into requests queue and will keep retrying

### ISSUE THREAD

**Issue by atg22896** [linuxserver/docker-ombi#82]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When adding it a request, it will do so without this error message.
## Current Behavior

When a request is added, this notification is sent in addition to the normal approval notification. The request is actually immediately added and is sent as expected.
This has not always happened, started happening like a month ago when I updated image. I don't know what previous image was before, but it has next been fixed with any image updates.
## Steps to Reproduce

1. Make request
2. Get this notification

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64

## Command used to create docker container (run/create/compose/screenshot)

```
    ombi:
        image: ghcr.io/linuxserver/ombi
        container_name: ombi
        environment:
            - PUID=999
            - PGID=1002
            - TZ=America/New_York
            - BASE_URL=/ombi #optional
        volumes:
            - /home/alex/docker/ombi/config:/config
        ports:
            - 3579:3579
        restart: unless-stopped
```
## Docker logs

[ombi.log](https://github.com/linuxserver/docker-ombi/files/5749026/ombi.log)
