### ISSUE TITLE
failed to create coreclr, hresult: "0x8007ff02"

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [linuxserver/docker-ombi#92]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Service container gets pulled and starts successfully
## Current Behavior

Service fails to run with error `failed to create coreclr, hresult: 0x8007ff02`
## Steps to Reproduce

1.Pull the image with the below docker compose file
2.Attempt to start the container
3.Monitor container logs

From a bit of googling, it seems that this is due to the process not having any available memory. I have tried adding `cap_add: IPC_LOCK` in my docker compose file to resolve the issue, and have also tried manually building the container with ` libcap2-bin` included and `setcap cap_ipc_lock=+eip /opt/ombi/Ombi` added to the run script.

I have tried this on a fresh restart of my machine and nothing seems to work.

## Environment
**OS:** Ubuntu 20.04 LTS
**CPU architecture:** x86_64
**How docker service was installed:**

From Linux Server container repository using docker compose

## Command used to create docker container (run/create/compose/screenshot)

Docker compose:
```yaml
  ombi:
    hostname: ombi
    image: ghcr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    depends_on:
      - traefik
      - mariadb
    volumes:
      - type: volume
        source: ombi-config
        target: /config
        read_only: False
    networks:
      - reverse_proxy
      - database
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      traefik.enable: True
      traefik.backend: ombi
      traefik.frontend.rule: "Host:ombi.${DOMAINNAME}; AddPrefix: /ombi"
      traefik.port: 3579
      traefik.docker.network: docker_reverse_proxy
```
Service was brought up using `docker-compose -f docker-compose.yml up -d`

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Ombi - Patreon: https://patreon.com/tidusjar
Ombi - PayPal: https://paypal.me/PlexRequestsNet
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
User uid:    1000
User gid:    999
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Failed to create CoreCLR, HRESULT: 0x8007FF02
```
