### ISSUE TITLE
Omby not reachable via localhost

### ISSUE THREAD

**Issue by GAS85** [linuxserver/docker-ombi#97]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Run container and reach it via exposed port on a localhost, e.g.

```bash
curl http://localhost:3579
```

## Current Behavior
Container is not accessible for a localhost machine with current configuration, nor reverse proxy, nor curl will works, only accessible from other containers, or other machines in network:

```bash
curl http://localhost:3579 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
```

## Steps to Reproduce

1. Use docker compose with following configuration:
    ```yaml
    version: "3.6"
    services:
      ombi:
        container_name: ombi
        restart: always
        image: lscr.io/linuxserver/ombi
        volumes:
          - ${WORKINGDIR}/docker/ombi:/config
          - ${WORKINGDIR}/docker/shared:/shared
        restart: unless-stopped
        ports:
          - 3579:3579
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
    ```
3. Check if port exposed and try to connect to it:
    ```bash
    $ docker ps -l
    CONTAINER ID   IMAGE                      COMMAND   CREATED          STATUS          PORTS                                       NAMES
    c590bcbcb8ca   lscr.io/linuxserver/ombi   "/init"   55 seconds ago   Up 54 seconds   0.0.0.0:3579->3579/tcp, :::3579->3579/tcp   ombi
    $ curl http://localhost:3579 
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed

      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
      0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
    ```
5. See that it is not accessible, change network configuration to host:
    ```yaml
    version: "3.6"
    services:
      ombi:
        container_name: ombi
        restart: always
        image: lscr.io/linuxserver/ombi
        volumes:
          - ${WORKINGDIR}/docker/ombi:/config
          - ${WORKINGDIR}/docker/shared:/shared
        restart: unless-stopped
        network_mode: "host"
        #ports:
        #  - 3579:3579
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
    ```
7. Check that it is accessible now:
    ```bash
    $ docker ps -l
    CONTAINER ID   IMAGE                      COMMAND   CREATED          STATUS          PORTS     NAMES
    4756fe84ccae   lscr.io/linuxserver/ombi   "/init"   11 seconds ago   Up 10 seconds             ombi
    $ curl http://localhost:3579
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!DOCTYPE html><html lang="en"><head><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">  
        <script type='text/javascript'>window["baseHref"] = '/ombi';</script>
    ...
    ```

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** from the official docker repo 
**Docker version:** 20.10.13

## Command used to create docker container (run/create/compose/screenshot)
```bash
docker-compose -f /var/docker/docker-compose.yaml up -d
```
content of `/var/docker/docker-compose.yaml`

```yaml
version: "3.6"
  ombi:
    container_name: ombi
    restart: always
    image: lscr.io/linuxserver/ombi
    volumes:
      - ${WORKINGDIR}/docker/ombi:/config
      - ${WORKINGDIR}/docker/shared:/shared
    restart: unless-stopped
    network_mode: "host"
#    ports:
#      - 3579:3579
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Ombi - Patreon: https://patreon.com/tidusjar
Ombi - PayPal: https://paypal.me/PlexRequestsNet

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    998
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Hello, welcome to Ombi
Valid options are:
Ombi 4.16.12
Copyright (C) 2022 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.



Wrote new baseurl at /opt/ombi/ClientApp/dist/index.html
We are running on http://*:3579
/opt/ombi

```
